### ISSUE TITLE
Support for reference as Value in Key Value pair?

### ISSUE THREAD

**Issue by GMZlate** [lpgauth/foil#2]
Hi, I'm trying to integrate Foil in to one of our project where we need to store corresponding references of counters in to Foil. However it doesn't seem to be supported and we got error stating: foil_compiler:to_syntax(......). Is there any solutions for storing Refs in the table? Thanks!

**Comment by lpgauth** [comment]
Hi @GMZlate,
Unfortunately, references are not literals and therefore cannot be compiled into code. Encoding them as integers does seem to work but it's an undocumented behavior...

https://github.com/erlang/otp/pull/1644

**Comment by lpgauth** [comment]
This functionality will be supported once OTP-21 is out. See https://github.com/lpgauth/foil/issues/6 for updates.
